CREATE SCHEMA catalog;

-- configure 'readonly' role access
GRANT USAGE ON SCHEMA catalog TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA catalog TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT SELECT ON TABLES TO readonly;

-- configure 'readwrite' role access
GRANT USAGE, CREATE ON SCHEMA catalog TO readwrite;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA catalog TO readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA catalog TO readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT USAGE ON SEQUENCES TO readwrite;